// <auto-generated />
using System;
using CloudKnowledge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CloudKnowledge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CloudKnowledgeDbContext))]
    [Migration("20260823215943_AddDocumentChunkEmbeddings")]
    partial class AddDocumentChunkEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudKnowledge.Domain.Documents.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .IsDescending(true, false)
                        .HasDatabaseName("IX_documents_created_at_utc_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("CloudKnowledge.Domain.Documents.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_document_chunks_document_id_position");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("CloudKnowledge.Infrastructure.Persistence.Models.DocumentChunkEmbeddingRow", b =>
                {
                    b.Property<Guid>("ChunkId")
                        .HasColumnType("uuid")
                        .HasColumnName("chunk_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.HasKey("ChunkId");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_document_chunk_embeddings_document_id");

                    b.ToTable("document_chunk_embeddings", (string)null);
                });

            modelBuilder.Entity("CloudKnowledge.Domain.Documents.DocumentChunk", b =>
                {
                    b.HasOne("CloudKnowledge.Domain.Documents.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CloudKnowledge.Infrastructure.Persistence.Models.DocumentChunkEmbeddingRow", b =>
                {
                    b.HasOne("CloudKnowledge.Domain.Documents.DocumentChunk", null)
                        .WithOne()
                        .HasForeignKey("CloudKnowledge.Infrastructure.Persistence.Models.DocumentChunkEmbeddingRow", "ChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
